#!/usr/bin/env bash
# install nginx on your web-01 server
# Nginx should be listening on port 80

sudo apt-get update -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
errorMsg="\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n}"
sed -i "s/^}$/$errorMsg/" /etc/nginx/sites-available/default
service nginx restart
