#!/usr/bin/env bash
#to configure a new server

apt-get update
apt-get -y install nginx
service nginx start
sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | tee /var/www/html/index.html
service nginx restart
