#!/usr/bin/env bash
#Prints 'bad luck' for i == 4, 'good luck' for i == 8 and 'Best School' for rest
i=1
while [ $i -lt 11 ];
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
