#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 44.197.204.55
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
